### ISSUE TITLE
Unusable with Webpack?

### ISSUE THREAD

**Issue by brandondurham** [dbtedman/postcss-prefixwrap#1]
Hiya,

Thanks for the plug-in! Question for you. I’m using `postcss` in a Webpack setup alongside CSS Modules. This requires `css-loader` be run _after_ postcss and, in turn, means `css-loader` will fail because `postcss-prefixwrap` has added a wrapper class. This is an issue with CSS Modules… you can’t `compose` nested classes.

Do you know if there is a way around this problem?

**Comment by dbtedman** [comment]
Hi,

Thanks for the feedback.

Are you able to provided an example webpack config showing how you use `css-loader` and `postcss` with css modules as I have not used this combination before. (I will update the following example once I have that example)

**Possible solution:**

Have you tried running two instances of the `postcss-loader` as I have tested that Webpack is perfectly happy with doing this.

The following example is using `style-loader` which is loading just some standard css (not using css modules):

`/src/bundle.js`

```javascript
import "./css/apple.css";
```
`/src/css/apple.css`

```css
body {
  background: rgba(153, 221, 153, 0.8);
}
```

```html
<html>
<head>
  <script src="./out/bundle.js"></script>
</head>
<body>
<div class="my-custom-wrap">
  <p>Hello World</p>
</div>
</body>
</html>
```

`/webpack.config.js`

```javascript
module.exports = {
  entry: "./src/bundle.js",
  output: {
    path: `${__dirname}/out`,
    filename: "bundle.js"
  },
  module: {
    rules: [{
      test: /\.css/,
      loaders: [
        "style-loader",
        {
          loader: "postcss-loader",
          options: {
            plugins: [
              require("postcss-color-rgba-fallback")()
            ]
          },
        },
        // css-loader or other loaders could be run here.
        {
          loader: "postcss-loader",
          options: {
            plugins: [
              require("postcss-prefixwrap")(".my-custom-wrap")
            ]
          },
        },
      ],
      include: `${__dirname}/src/css`
    }]
  }
};
```

When I use this config, I see the Hello World text on a green background using the hex representation of the colour. This shows that both postcss-loader instances ran successfully.

Hope this helps.
