### ISSUE TITLE
The name of the latest release should be 1.26.0 but is 1.16.0

### ISSUE THREAD

**Issue by Konafets** [dbtedman/postcss-prefixwrap#139]
Hi,

as you can see from the screenshot the tag is correct while the title of the release is wrong.

![2021-12-11_16-32-45](https://user-images.githubusercontent.com/363363/145682236-b8e387fe-590d-4ef8-b49f-4643945bc443.jpg)

**Comment by dbtedman** [comment]
Thanks @Konafets, I have updated it accordingly
