### ISSUE TITLE
PostCSS plugin postcss-prefixwrap requires PostCSS 8

### ISSUE THREAD

**Issue by hrgondaliya** [dbtedman/postcss-prefixwrap#149]
I am getting this error whenever I run "npm run build:new". I tried a couple of fixes but none of them work for me. I have updated by react script to "^5.0.0", and then I am started to get this error. I tried to change the version of postcss-prefixwrap to the latest v1.28.1 but it didn't work. Please help me with this issue.

In an earlier ticket, the comment is posted that "postcss-prefixwrap" should work with postcss v8. but it does not work with that.

https://github.com/dbtedman/postcss-prefixwrap/issues/140#issuecomment-1008612873

This is my package.json
`{
  "name": "components-web",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@e-builder/react-components": "^1.0.41",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-regular-svg-icons": "^5.12.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/pro-light-svg-icons": "^5.12.1",
    "@fortawesome/pro-regular-svg-icons": "^5.12.1",
    "@fortawesome/pro-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "ajv": "^6.12.0",
    "antd": "^4.16.13",
    "apollo-boost": "^0.4.9",
    "aws-sdk": "^2.997.0",
    "axios": "^0.21.4",
    "bluebird": "^3.7.2",
    "cluster": "^0.7.7",
    "compression": "^1.7.1",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.6.11",
    "cors": "^2.8.5",
    "crypto-js": "^3.3.0",
    "customize-cra": "^0.6.1",
    "evaporate": "^2.1.4",
    "express": "^4.16.2",
    "file-saver": "^1.3.8",
    "graphql": "^16.2.0",
    "helmet": "^3.21.3",
    "immutability-helper": "^3.0.1",
    "jquery": "^3.5.1",
    "mobx": "^4.15.4",
    "mobx-react": "^5.2.0",
    "moment": "^2.22.2",
    "morgan": "^1.9.0",
    "postcss": "^8.2.15",
    "postcss-prefixwrap": "^1.28.1",
    "primeicons": "^1.0.0",
    "primereact": "^3.4.0",
    "prop-types": "^15.6.1",
    "qrcode.react": "^0.9.3",
    "react": "^16.12.0",
    "react-apollo": "^2.1.9",
    "react-app-rewire-postcss": "^3.0.2",
    "react-app-rewired": "^2.1.5",
    "react-compound-timer": "^1.1.15",
    "react-dom": "^16.12.0",
    "react-resizable": "^3.0.4",
    "react-scripts": "^5.0.0",
    "react-test-renderer": "^16.12.0",
    "react-transition-group": "^2.9.0",
    "typescript": "^4.4.3",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "eslint": "^7.32.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jest": "^22.21.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.26.1",
    "source-map-explorer": "^2.3.1"
  },
  "scripts": {
    "analyze": "source-map-explorer build/static/js/main.*",
    "start": "mkdir -p dist/static && node eb_app_config && npm run build && npm run build:new && node app",
    "start:test": "npm run test:nowatch && npm run start",
    "copy:global:new": "copy .\\dist\\global-functions.js > .\\dist\\components.new.js",
    "copy:media": "copy -r .\\build\\static\\media .\\dist\\static\\media",
    "build": "node set-build-bundle index-default.js && NODE_ENV='production' react-app-rewired build && npm run copy:build",
    "start:dev": "node set-build-bundle index-default.js && NODE_ENV='development' react-app-rewired start",
    "copy:js:new": "copy .\\build\\static\\js\\main*.js >> .\\dist\\components.new.js",
    "copy:css:new": "copy .\\build\\static\\css\\main*.css .\\dist\\components.new.css",
    "copy:build:new": "npm run copy:global:new && npm run copy:js:new && npm run copy:css:new ",
    "build:new": "node set-build-bundle index-new-ux.js && NODE_ENV='production' react-app-rewired build && npm run copy:build:new",
    "start:dev:new": "node set-build-bundle index-new-ux.js && NODE_ENV='development' react-app-rewired start",
    "test": "react-app-rewired test --env=jsdom",
    "test:nowatch": "node eb_app_config && CI=true react-app-rewired test --env=jsdom",
    "eject": "react-app-rewired eject",
    "test:lint": "eslint . --ext .js"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "babel": {
    "env": {
      "test": {
        "plugins": [
          [
            "@babel/plugin-proposal-decorators",
            {
              "legacy": true
            }
          ]
        ]
      }
    }
  }
}
`

**Comment by dbtedman** [comment]
Hi @hrgondaliya as explained in https://github.com/dbtedman/postcss-prefixwrap/issues/140#issuecomment-1009862862 I believe the issue to be because of another plugin as outlined in the console output and not this one.
