### ISSUE TITLE
Add ability to replace the :root pseudo-class directly or through generic addition

### ISSUE THREAD

**Issue by greatwillow** [dbtedman/postcss-prefixwrap#163]
Hi @dbtedman,  

Thanks for this plugin as it seems to be working well overall, however, I am just noticing that it will not work for css with the :root pseudo-class.  Looking at the purpose of this plugin, it seems that this should also be replaced upon processing.  

It seems in this case, the easiest solution to this problem would be to modify 'IS_ROOT_TAG' inside Selector.ts to be 

```ts
const IS_ROOT_TAG = /^(body|html|:root).*$/;
```

or alternatively, to perhaps create an option for more generic usage while allowing this to be 'opt in' and more backwards compatible.  Perhaps, for example, and 'additionalRootTags' array option could be passed in and used to costruct a dynamically built root tag regex here.

What are your thoughts on this?

**Comment by dbtedman** [comment]
@greatwillow this update has been released to NPM.

**Comment by greatwillow** [comment]
@dbtedman Thanks for adding this!  Well appreciated!
