### ISSUE TITLE
how to use in webpack5?

### ISSUE THREAD

**Issue by evilpose** [dbtedman/postcss-prefixwrap#171]
how to use in webpack5?

**Comment by dbtedman** [comment]
Hi @evilpose, the instructions for use with webpack will be the same as for any postcss plugin. You will want to use https://webpack.js.org/loaders/postcss-loader/. PostCSS PrefixWrap is then just provided as one of the list of plugins.

Based on the example from the page listed above, you would want something like the following:

```
// webpack.config.js 
const PrefixWrap = require("postcss-prefixwrap");

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          "style-loader",
          "css-loader",
          {
            loader: "postcss-loader",
            options: {
              postcssOptions: {
                plugins: [
                 PrefixWrap(".my-custom-wrap")
                ],
              },
            },
          },
        ],
      },
    ],
  },
};
```
