### ISSUE TITLE
Using "/" path separator in "whitelist", "blacklist" config doesn't work in windows env

### ISSUE THREAD

**Issue by paulbennet** [dbtedman/postcss-prefixwrap#176]
Internally the "patterns" provided via `whitelist`, `blacklist` options are "Regex matched" against the current CSS file's "path" during post-css execution.

Check code here -> https://github.com/dbtedman/postcss-prefixwrap/blob/main/src/PostCSSPrefixWrap.ts#L113

The docs doesn't mention this explicitly. Instead it just specifies "File" whitelist & "File" blacklist.
![image](https://user-images.githubusercontent.com/4631143/183925887-e768566c-83a8-4c87-9491-4259f57badf3.png)

Users may think that they can provide file paths in these configs and later suffer when running same projects in different env (windows), due to different path separator patterns.

--

Explicitly mentioning that the whitelist, blacklist options are actually Rx patterns, will help users avoid these platform issues.

**Comment by dbtedman** [comment]
Thanks @paulbennet for the feedback, I will update the documentation to clarify this to help users in future.
