### ISSUE TITLE
Cannot compile with `tsc` (was: "1.34.0 -> 1.35.1 broke the types")

### ISSUE THREAD

**Issue by martinml** [dbtedman/postcss-prefixwrap#189]
In `1.34.0`, the plugin is properly being typed as `PostCSSAcceptedPlugin`, but in `1.35.1`, it's `any`.

It seems that `build/index.d.ts` is trying to import the types from the wrong place? 🤔

```ts
declare const _default: import("./Types").PostCSS8Plugin | import("./Types").PostCSS7Plugin;
```

**Comment by dbtedman** [comment]
Thanks @martinml for reporting this issue, I have done some refactoring lately that seems to have had some unintended consequences. I will work to resolve this issue, then expand on my integration testing to avoid this happening in future.

**Comment by dbtedman** [comment]
@martinml I am about to prepare `1.36.0` release which should resolve this issue
