### ISSUE TITLE
bug: `dist/main.js` missing in published package since 1.8.0

### ISSUE THREAD

**Issue by sbusch** [dbtedman/postcss-prefixwrap#62]
With 1.8.0 I get this error:

    Error: Cannot find module
    '/Users/developer/Devel/qbus-js/node_modules/postcss-prefixwrap/dist/main.js'.
    Please verify that the package.json has a valid "main" entry

**Comment by dbtedman** [comment]
Hi @sbusch thanks for reporting this bug. Looks like I did not correctly test the published output after switching to a TypeScript build. I have fixed the issue, added additional integration tests as well as manually testing the package. All should be resolved in the 1.9.0 release.

**Comment by sbusch** [comment]
Thanks @dbtedman
